### PR TITLE
Remove old authenticatio

### LINKED ISSUE #24: 💡 [REQUEST] - Remove old authentication
### Summary

Before integrating auth0, we need to remove the old authentication.

### Basic Example

None

### General things to do

- [ ] Remove old authentication

### Unresolved questions

_No response_

### PR DESCRIPTION
**Pull request by yuenci**
### Please tell us what you did
    1. "/login" navigate to "/"
    2. Remove authentication detection on frame
    3. Create mock user data on status container(ModalStore)

### Are there any concerns that may be raised ?
No

### Please add which issue does this PR close below using ("closes #issue_number")
closes #24

### CODE REVIEW

**Review by ETCasual — COMMENTED** [review]
Im thinking whether we should also remove all api calls as well. like those `postReq`, `fetchReq` functions as we are starting anew. @yuenci  what do u think, or we ask the ones working on it to change themselves

**Comment by yuenci** [comment]
I don't think so, we don't have any api calls about user auth any more,  so we can start to integrate Auth0 to ERP. Other api calls all about recruitment, we will deal with recruitment later

**Comment by ETCasual** [comment]
also , run `yarn lint` before u commit so u know where else has issues

> I don't think so, we don't have any api calls about user auth any more, so we can start to integrate Auth0 to ERP. Other api calls all about recruitment, we will deal with recruitment later

Okay, btw, ive pulled ur branch, and it seems like there are some type mismatch, im gonna fix it and also because of this i realised theres a need to check type errors, im gonna add a `precommit` check as well

**Review by ETCasual — APPROVED** [review]
LGTM

**Pull request merged**
